name: google_maps_cross
description: Google maps cross platform
version: 1.0.2
homepage: https://github.com/zapiti/google_maps_cross

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_polyline_algorithm: 3.1.0
  google_maps_flutter: 2.1.5
  google_directions_api: 0.9.1
  google_maps: 6.1.0
  http: 0.13.4
  flinq: 2.0.2
  uuid: 3.0.6
  universal_html: 2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker_a.png
    - assets/images/marker_b.png