name: google_maps_cross
description: Google maps cross platform
version: 1.0.0
authors: [zapiti]
homepage: https://github.com/zapiti/google_maps_cross

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_polyline_algorithm: ^3.1.0
  google_maps_flutter: 2.0.6
  google_directions_api: ^0.9.0
  google_maps: ^5.1.0
  http: ^0.13.3
  flinq: ^2.0.2
  uuid: ^3.0.4
  universal_html: 2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/marker_a.png
    - assets/images/marker_b.png